spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: maria
    password: p@ssw0rd

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl.auto: create