server:
  port: 8082
  servlet:
    contextPath: /api

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        hdm2ddl.auto: create
        format_sql: true

  output:
    ansi:
      enabled: always

  profiles:
    include: local


  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093,localhost:9094
      bindings:
        orderCreated:
          destination: order-created
          group: order-service
        paymentCompleted:
          destination: payment-completed
          group: order-service


jwt:
  header: Authorization
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw
  access-token-validity-in-seconds: 3600 # 1 hour
  refresh-token-validity-in-seconds: 86400 # 1 day

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: debug
