server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  profiles:
    include: db


jwt:
  header: Authorization
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw
  access-token-validity-in-seconds: 3600 # 1 hour
  refresh-token-validity-in-seconds: 86400 # 1 day

