server:
  port: 8081
#  servlet:
#    contextPath: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        hdm2ddl.auto: create
        format_sql: true

  output:
    ansi:
      enabled: always

  profiles:
    include:
      - local

jwt:
  header: Authorization
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw
  access-token-validity-in-seconds: 3600 # 1 hour
  refresh-token-validity-in-seconds: 86400 # 1 day

logging:
  level:
    org.hibernate.type: TRACE