
jwt:
  header: Authorization
  secret: Q4NSl604sgyHJj1qwEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSF4XXyYJkal13eqgB0F7Bq4H
  access-token-validity-in-seconds: 3600 # 1 hour
  refresh-token-validity-in-seconds: 86400 # 1 day