server:
  port: 8084
  servlet:
    contextPath: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        hdm2ddl.auto: update
        format_sql: true

  output:
    ansi:
      enabled: always

  profiles:
    include: local

jwt:
  header: Authorization
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw
  access-token-validity-in-seconds: 3600 # 1 hour
  refresh-token-validity-in-seconds: 86400 # 1 day

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: debug